// Periodic table data — 118 elements.
// Fields: n=atomic number, s=symbol, name, mass=standard atomic weight,
// category (used for color), x/y = column/row in the rendered grid.
// Lanthanides (y=9) and actinides (y=10) are placed in the two separated rows
// below the main table, matching the conventional 18-column layout.

export const elements = [
  { n: 1,   s: "H",  name: "Hydrogen",      mass: 1.008,   category: "nonmetal",        x: 1,  y: 1 },
  { n: 2,   s: "He", name: "Helium",        mass: 4.0026,  category: "noble-gas",       x: 18, y: 1 },

  { n: 3,   s: "Li", name: "Lithium",       mass: 6.94,    category: "alkali-metal",    x: 1,  y: 2 },
  { n: 4,   s: "Be", name: "Beryllium",     mass: 9.0122,  category: "alkaline-earth",  x: 2,  y: 2 },
  { n: 5,   s: "B",  name: "Boron",         mass: 10.81,   category: "metalloid",       x: 13, y: 2 },
  { n: 6,   s: "C",  name: "Carbon",        mass: 12.011,  category: "nonmetal",        x: 14, y: 2 },
  { n: 7,   s: "N",  name: "Nitrogen",      mass: 14.007,  category: "nonmetal",        x: 15, y: 2 },
  { n: 8,   s: "O",  name: "Oxygen",        mass: 15.999,  category: "nonmetal",        x: 16, y: 2 },
  { n: 9,   s: "F",  name: "Fluorine",      mass: 18.998,  category: "halogen",         x: 17, y: 2 },
  { n: 10,  s: "Ne", name: "Neon",          mass: 20.180,  category: "noble-gas",       x: 18, y: 2 },

  { n: 11,  s: "Na", name: "Sodium",        mass: 22.990,  category: "alkali-metal",    x: 1,  y: 3 },
  { n: 12,  s: "Mg", name: "Magnesium",     mass: 24.305,  category: "alkaline-earth",  x: 2,  y: 3 },
  { n: 13,  s: "Al", name: "Aluminium",     mass: 26.982,  category: "post-transition", x: 13, y: 3 },
  { n: 14,  s: "Si", name: "Silicon",       mass: 28.085,  category: "metalloid",       x: 14, y: 3 },
  { n: 15,  s: "P",  name: "Phosphorus",    mass: 30.974,  category: "nonmetal",        x: 15, y: 3 },
  { n: 16,  s: "S",  name: "Sulfur",        mass: 32.06,   category: "nonmetal",        x: 16, y: 3 },
  { n: 17,  s: "Cl", name: "Chlorine",      mass: 35.45,   category: "halogen",         x: 17, y: 3 },
  { n: 18,  s: "Ar", name: "Argon",         mass: 39.948,  category: "noble-gas",       x: 18, y: 3 },

  { n: 19,  s: "K",  name: "Potassium",     mass: 39.098,  category: "alkali-metal",    x: 1,  y: 4 },
  { n: 20,  s: "Ca", name: "Calcium",       mass: 40.078,  category: "alkaline-earth",  x: 2,  y: 4 },
  { n: 21,  s: "Sc", name: "Scandium",      mass: 44.956,  category: "transition",      x: 3,  y: 4 },
  { n: 22,  s: "Ti", name: "Titanium",      mass: 47.867,  category: "transition",      x: 4,  y: 4 },
  { n: 23,  s: "V",  name: "Vanadium",      mass: 50.942,  category: "transition",      x: 5,  y: 4 },
  { n: 24,  s: "Cr", name: "Chromium",      mass: 51.996,  category: "transition",      x: 6,  y: 4 },
  { n: 25,  s: "Mn", name: "Manganese",     mass: 54.938,  category: "transition",      x: 7,  y: 4 },
  { n: 26,  s: "Fe", name: "Iron",          mass: 55.845,  category: "transition",      x: 8,  y: 4 },
  { n: 27,  s: "Co", name: "Cobalt",        mass: 58.933,  category: "transition",      x: 9,  y: 4 },
  { n: 28,  s: "Ni", name: "Nickel",        mass: 58.693,  category: "transition",      x: 10, y: 4 },
  { n: 29,  s: "Cu", name: "Copper",        mass: 63.546,  category: "transition",      x: 11, y: 4 },
  { n: 30,  s: "Zn", name: "Zinc",          mass: 65.38,   category: "transition",      x: 12, y: 4 },
  { n: 31,  s: "Ga", name: "Gallium",       mass: 69.723,  category: "post-transition", x: 13, y: 4 },
  { n: 32,  s: "Ge", name: "Germanium",     mass: 72.630,  category: "metalloid",       x: 14, y: 4 },
  { n: 33,  s: "As", name: "Arsenic",       mass: 74.922,  category: "metalloid",       x: 15, y: 4 },
  { n: 34,  s: "Se", name: "Selenium",      mass: 78.971,  category: "nonmetal",        x: 16, y: 4 },
  { n: 35,  s: "Br", name: "Bromine",       mass: 79.904,  category: "halogen",         x: 17, y: 4 },
  { n: 36,  s: "Kr", name: "Krypton",       mass: 83.798,  category: "noble-gas",       x: 18, y: 4 },

  { n: 37,  s: "Rb", name: "Rubidium",      mass: 85.468,  category: "alkali-metal",    x: 1,  y: 5 },
  { n: 38,  s: "Sr", name: "Strontium",     mass: 87.62,   category: "alkaline-earth",  x: 2,  y: 5 },
  { n: 39,  s: "Y",  name: "Yttrium",       mass: 88.906,  category: "transition",      x: 3,  y: 5 },
  { n: 40,  s: "Zr", name: "Zirconium",     mass: 91.224,  category: "transition",      x: 4,  y: 5 },
  { n: 41,  s: "Nb", name: "Niobium",       mass: 92.906,  category: "transition",      x: 5,  y: 5 },
  { n: 42,  s: "Mo", name: "Molybdenum",    mass: 95.95,   category: "transition",      x: 6,  y: 5 },
  { n: 43,  s: "Tc", name: "Technetium",    mass: 98,      category: "transition",      x: 7,  y: 5 },
  { n: 44,  s: "Ru", name: "Ruthenium",     mass: 101.07,  category: "transition",      x: 8,  y: 5 },
  { n: 45,  s: "Rh", name: "Rhodium",       mass: 102.91,  category: "transition",      x: 9,  y: 5 },
  { n: 46,  s: "Pd", name: "Palladium",     mass: 106.42,  category: "transition",      x: 10, y: 5 },
  { n: 47,  s: "Ag", name: "Silver",        mass: 107.87,  category: "transition",      x: 11, y: 5 },
  { n: 48,  s: "Cd", name: "Cadmium",       mass: 112.41,  category: "transition",      x: 12, y: 5 },
  { n: 49,  s: "In", name: "Indium",        mass: 114.82,  category: "post-transition", x: 13, y: 5 },
  { n: 50,  s: "Sn", name: "Tin",           mass: 118.71,  category: "post-transition", x: 14, y: 5 },
  { n: 51,  s: "Sb", name: "Antimony",      mass: 121.76,  category: "metalloid",       x: 15, y: 5 },
  { n: 52,  s: "Te", name: "Tellurium",     mass: 127.60,  category: "metalloid",       x: 16, y: 5 },
  { n: 53,  s: "I",  name: "Iodine",        mass: 126.90,  category: "halogen",         x: 17, y: 5 },
  { n: 54,  s: "Xe", name: "Xenon",         mass: 131.29,  category: "noble-gas",       x: 18, y: 5 },

  { n: 55,  s: "Cs", name: "Caesium",       mass: 132.91,  category: "alkali-metal",    x: 1,  y: 6 },
  { n: 56,  s: "Ba", name: "Barium",        mass: 137.33,  category: "alkaline-earth",  x: 2,  y: 6 },
  { n: 57,  s: "La", name: "Lanthanum",     mass: 138.91,  category: "lanthanide",      x: 3,  y: 9 },
  { n: 58,  s: "Ce", name: "Cerium",        mass: 140.12,  category: "lanthanide",      x: 4,  y: 9 },
  { n: 59,  s: "Pr", name: "Praseodymium",  mass: 140.91,  category: "lanthanide",      x: 5,  y: 9 },
  { n: 60,  s: "Nd", name: "Neodymium",     mass: 144.24,  category: "lanthanide",      x: 6,  y: 9 },
  { n: 61,  s: "Pm", name: "Promethium",    mass: 145,     category: "lanthanide",      x: 7,  y: 9 },
  { n: 62,  s: "Sm", name: "Samarium",      mass: 150.36,  category: "lanthanide",      x: 8,  y: 9 },
  { n: 63,  s: "Eu", name: "Europium",      mass: 151.96,  category: "lanthanide",      x: 9,  y: 9 },
  { n: 64,  s: "Gd", name: "Gadolinium",    mass: 157.25,  category: "lanthanide",      x: 10, y: 9 },
  { n: 65,  s: "Tb", name: "Terbium",       mass: 158.93,  category: "lanthanide",      x: 11, y: 9 },
  { n: 66,  s: "Dy", name: "Dysprosium",    mass: 162.50,  category: "lanthanide",      x: 12, y: 9 },
  { n: 67,  s: "Ho", name: "Holmium",       mass: 164.93,  category: "lanthanide",      x: 13, y: 9 },
  { n: 68,  s: "Er", name: "Erbium",        mass: 167.26,  category: "lanthanide",      x: 14, y: 9 },
  { n: 69,  s: "Tm", name: "Thulium",       mass: 168.93,  category: "lanthanide",      x: 15, y: 9 },
  { n: 70,  s: "Yb", name: "Ytterbium",     mass: 173.05,  category: "lanthanide",      x: 16, y: 9 },
  { n: 71,  s: "Lu", name: "Lutetium",      mass: 174.97,  category: "lanthanide",      x: 17, y: 9 },
  { n: 72,  s: "Hf", name: "Hafnium",       mass: 178.49,  category: "transition",      x: 4,  y: 6 },
  { n: 73,  s: "Ta", name: "Tantalum",      mass: 180.95,  category: "transition",      x: 5,  y: 6 },
  { n: 74,  s: "W",  name: "Tungsten",      mass: 183.84,  category: "transition",      x: 6,  y: 6 },
  { n: 75,  s: "Re", name: "Rhenium",       mass: 186.21,  category: "transition",      x: 7,  y: 6 },
  { n: 76,  s: "Os", name: "Osmium",        mass: 190.23,  category: "transition",      x: 8,  y: 6 },
  { n: 77,  s: "Ir", name: "Iridium",       mass: 192.22,  category: "transition",      x: 9,  y: 6 },
  { n: 78,  s: "Pt", name: "Platinum",      mass: 195.08,  category: "transition",      x: 10, y: 6 },
  { n: 79,  s: "Au", name: "Gold",          mass: 196.97,  category: "transition",      x: 11, y: 6 },
  { n: 80,  s: "Hg", name: "Mercury",       mass: 200.59,  category: "transition",      x: 12, y: 6 },
  { n: 81,  s: "Tl", name: "Thallium",      mass: 204.38,  category: "post-transition", x: 13, y: 6 },
  { n: 82,  s: "Pb", name: "Lead",          mass: 207.2,   category: "post-transition", x: 14, y: 6 },
  { n: 83,  s: "Bi", name: "Bismuth",       mass: 208.98,  category: "post-transition", x: 15, y: 6 },
  { n: 84,  s: "Po", name: "Polonium",      mass: 209,     category: "post-transition", x: 16, y: 6 },
  { n: 85,  s: "At", name: "Astatine",      mass: 210,     category: "halogen",         x: 17, y: 6 },
  { n: 86,  s: "Rn", name: "Radon",         mass: 222,     category: "noble-gas",       x: 18, y: 6 },

  { n: 87,  s: "Fr", name: "Francium",      mass: 223,     category: "alkali-metal",    x: 1,  y: 7 },
  { n: 88,  s: "Ra", name: "Radium",        mass: 226,     category: "alkaline-earth",  x: 2,  y: 7 },
  { n: 89,  s: "Ac", name: "Actinium",      mass: 227,     category: "actinide",        x: 3,  y: 10 },
  { n: 90,  s: "Th", name: "Thorium",       mass: 232.04,  category: "actinide",        x: 4,  y: 10 },
  { n: 91,  s: "Pa", name: "Protactinium",  mass: 231.04,  category: "actinide",        x: 5,  y: 10 },
  { n: 92,  s: "U",  name: "Uranium",       mass: 238.03,  category: "actinide",        x: 6,  y: 10 },
  { n: 93,  s: "Np", name: "Neptunium",     mass: 237,     category: "actinide",        x: 7,  y: 10 },
  { n: 94,  s: "Pu", name: "Plutonium",     mass: 244,     category: "actinide",        x: 8,  y: 10 },
  { n: 95,  s: "Am", name: "Americium",     mass: 243,     category: "actinide",        x: 9,  y: 10 },
  { n: 96,  s: "Cm", name: "Curium",        mass: 247,     category: "actinide",        x: 10, y: 10 },
  { n: 97,  s: "Bk", name: "Berkelium",     mass: 247,     category: "actinide",        x: 11, y: 10 },
  { n: 98,  s: "Cf", name: "Californium",   mass: 251,     category: "actinide",        x: 12, y: 10 },
  { n: 99,  s: "Es", name: "Einsteinium",   mass: 252,     category: "actinide",        x: 13, y: 10 },
  { n: 100, s: "Fm", name: "Fermium",       mass: 257,     category: "actinide",        x: 14, y: 10 },
  { n: 101, s: "Md", name: "Mendelevium",   mass: 258,     category: "actinide",        x: 15, y: 10 },
  { n: 102, s: "No", name: "Nobelium",      mass: 259,     category: "actinide",        x: 16, y: 10 },
  { n: 103, s: "Lr", name: "Lawrencium",    mass: 266,     category: "actinide",        x: 17, y: 10 },
  { n: 104, s: "Rf", name: "Rutherfordium", mass: 267,     category: "transition",      x: 4,  y: 7 },
  { n: 105, s: "Db", name: "Dubnium",       mass: 268,     category: "transition",      x: 5,  y: 7 },
  { n: 106, s: "Sg", name: "Seaborgium",    mass: 269,     category: "transition",      x: 6,  y: 7 },
  { n: 107, s: "Bh", name: "Bohrium",       mass: 270,     category: "transition",      x: 7,  y: 7 },
  { n: 108, s: "Hs", name: "Hassium",       mass: 269,     category: "transition",      x: 8,  y: 7 },
  { n: 109, s: "Mt", name: "Meitnerium",    mass: 278,     category: "unknown",         x: 9,  y: 7 },
  { n: 110, s: "Ds", name: "Darmstadtium",  mass: 281,     category: "unknown",         x: 10, y: 7 },
  { n: 111, s: "Rg", name: "Roentgenium",   mass: 282,     category: "unknown",         x: 11, y: 7 },
  { n: 112, s: "Cn", name: "Copernicium",   mass: 285,     category: "transition",      x: 12, y: 7 },
  { n: 113, s: "Nh", name: "Nihonium",      mass: 286,     category: "unknown",         x: 13, y: 7 },
  { n: 114, s: "Fl", name: "Flerovium",     mass: 289,     category: "unknown",         x: 14, y: 7 },
  { n: 115, s: "Mc", name: "Moscovium",     mass: 289,     category: "unknown",         x: 15, y: 7 },
  { n: 116, s: "Lv", name: "Livermorium",   mass: 293,     category: "unknown",         x: 16, y: 7 },
  { n: 117, s: "Ts", name: "Tennessine",    mass: 294,     category: "unknown",         x: 17, y: 7 },
  { n: 118, s: "Og", name: "Oganesson",     mass: 294,     category: "unknown",         x: 18, y: 7 },
];

export const categoryLabels = {
  "alkali-metal":    "Alkali metal",
  "alkaline-earth":  "Alkaline earth metal",
  "transition":      "Transition metal",
  "post-transition": "Post-transition metal",
  "metalloid":       "Metalloid",
  "nonmetal":        "Reactive nonmetal",
  "halogen":         "Halogen",
  "noble-gas":       "Noble gas",
  "lanthanide":      "Lanthanide",
  "actinide":        "Actinide",
  "unknown":         "Unknown / predicted",
};
